miningop/urls.py
from django.urls import path

from . import views

app_name = "miningop"

urlpatterns = [
    path("", views.index, name="index"),
    path("ops/<int:mining_op_id>", views.view, name="view"),
    path("ops/<int:mining_op_id>/start", views.start, name="start"),
    path("ops/<int:mining_op_id>/complete", views.complete, name="complete"),
    path("ops/<int:mining_op_id>/refresh", views.refresh, name="refresh"),
    path(
        "ops/<int:mining_op_id>/authenticate", views.authenticate_view, name="authenticate_view"
    ),
    path("create", views.create, name="create"),
    path("authenticate", views.authenticate_index, name="authenticate_index"),
]

miningop/templates/miningop/base.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}

{% block page_title %}{% translate "Mining Ops" %}{% endblock %}

{% block content %}
    <div class="allianceauth-mining-op-plugin">
        <h1 class="page-header text-center">{% translate "Mining Ops" %}</h1>

        {% block details %}{% endblock %}
    </div>
{% endblock %}

miningop/templates/miningop/characternotexisting.html
{% extends 'allianceauth/base.html' %}
{% load i18n %}
{% block page_title %}{% trans "Mining Ops" %}{% endblock %}

{% block content %}
<div class="col-lg-12">
    <h1 class="page-header text-center">{% trans "Character not found!" %}</h1>
    <div class="col-lg-12 container" id="example">
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">{{ character_name }}</div>
                    <div class="panel-body">
                        <div class="col-lg-2 col-sm-2">
                             <img class="ra-avatar img-responsive" src="{{ character_portrait_url }}">
                        </div>
                        <div class="col-lg-10 col-sm-2">
                            <div class="alert alert-danger" role="alert">{% trans "Character not registered!" %}</div>
                            {% trans "This character is not associated with an auth account." %} <a href=" {% url 'authentication:add_character' %}">{% trans "Add it here" %}</a> {% trans "before attempting to create mining ops." %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

miningop/templates/miningop/index.html
{% extends 'miningop/base.html' %}
{% load i18n %}
{% load humanize %}

{% block details %}

    {% if missing_tokens %}
        <div class="alert alert-danger" style="display: flex; align-items: center; justify-content: space-between;">
            <div>
                <div>{% trans "You do not have a mining ledger token on the following accounts:" %}</div>
                <div>{{ missing_tokens }}</div>
            </div>

            <form method="POST">
                {% csrf_token %}

                <button type="submit" class="btn btn-info" formaction="{% url 'miningop:authenticate_index' %}">
                    {% trans "Authenticate" %}
                </button>
            </form>
        </div>
    {% endif %}

    <div class="panel panel-primary">
        <div class="panel-heading" style="display: flex; align-items: center; justify-content: space-between;">
            <h3 class="panel-title">Active Mining Ops</h3>

            {% if can_manage %}
                <form method="POST">
                    {% csrf_token %}

                    <button type="submit" class="btn btn-sm btn-info" formaction="{% url 'miningop:create' %}">
                        {% trans "Create op" %}
                    </button>
                </form>
            {% endif %}
        </div>
        <div class="panel-body" style="min-height: 100px;">
            {% if active_mining_ops %}
                <div class="table-responsive">
                    <table class="table mining-op-list">
                        <thead>
                            <th class="text-center">{% trans "Fleet Commander" %}</th>
                            <th class="text-center">{% trans "Operation Status" %}</th>
                            <th class="text-center">{% trans "Created" %}</th>
                            <th class="text-center">{% trans "Started" %}</th>
                            <th class="text-center">{% trans "Completed" %}</th>
                            <th></th>
                        </thead>

                        <tbody>
                        {% for mining_op in active_mining_ops %}
                            <tr>
                                <td class="text-center" style="vertical-align: middle;">
                                    {% if mining_op.fleet_commander.alliance_ticker %}
                                        {{ mining_op.fleet_commander.alliance_ticker }}
                                    {% endif %}
                                    [{{ mining_op.fleet_commander.corporation_ticker }}]
                                    {{ mining_op.fleet_commander.character_name }}
                                </td>
                                <td class="text-center" style="vertical-align: middle;">
                                    {{ mining_op.status }}
                                </td>
                                <td class="text-center" style="vertical-align: middle;">
                                    {{ mining_op.created_at | date:"Y-M-d H:i" }}
                                </td>
                                <td class="text-center" style="vertical-align: middle;">
                                    {{ mining_op.started_at | date:"Y-M-d H:i" }}
                                </td>
                                <td class="text-center" style="vertical-align: middle;">
                                    {{ mining_op.completed_at | date:"Y-M-d H:i" }}
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'miningop:view' mining_op_id=mining_op.id %}" class="btn btn-sm btn-info">
                                        <span class="glyphicon glyphicon-eye-open"></span>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="alert alert-warning text-center">
                    {% trans "No active mining ops currently." %}
                </div>
            {% endif %}
        </div>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Mining Ops history</h3>
        </div>
        <div class="panel-body" style="min-height: 100px;">
            {% if inactive_mining_ops %}
                <div class="table-responsive">
                    <table class="table mining-op-list">
                        <thead>
                            <th class="text-center">{% trans "Fleet Commander" %}</th>
                            <th class="text-center">{% trans "Operation Status" %}</th>
                            <th class="text-center">{% trans "Created" %}</th>
                            <th class="text-center">{% trans "Started" %}</th>
                            <th class="text-center">{% trans "Completed" %}</th>
                            <th></th>
                        </thead>

                        <tbody>
                        {% for mining_op in inactive_mining_ops %}
                            <tr>
                                <td class="text-center" style="vertical-align: middle;">
                                    {% if mining_op.fleet_commander.alliance_ticker %}
                                        {{ mining_op.fleet_commander.alliance_ticker }}
                                    {% endif %}
                                    [{{ mining_op.fleet_commander.corporation_ticker }}]
                                    {{ mining_op.fleet_commander.character_name }}
                                </td>
                                <td class="text-center" style="vertical-align: middle;">
                                    {{ mining_op.status }}
                                </td>
                                <td class="text-center" style="vertical-align: middle;">
                                    {{ mining_op.created_at | date:"Y-M-d H:i" }}
                                </td>
                                <td class="text-center" style="vertical-align: middle;">
                                    {{ mining_op.started_at | date:"Y-M-d H:i" }}
                                </td>
                                <td class="text-center" style="vertical-align: middle;">
                                    {{ mining_op.completed_at | date:"Y-M-d H:i" }}
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'miningop:view' mining_op_id=mining_op.id %}" class="btn btn-sm btn-info">
                                        <span class="glyphicon glyphicon-eye-open"></span>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="alert alert-warning text-center">
                    {% trans "No mining ops yet." %}
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}

miningop/templates/miningop/view.html
{% extends 'miningop/base.html' %}
{% load i18n %}
{% load humanize %}

{% block details %}

    {% if missing_tokens %}
        <div class="alert alert-danger" style="display: flex; align-items: center; justify-content: space-between;">
            <div>
                <div>{% trans "You do not have a mining ledger token on the following accounts:" %}</div>
                <div>{{ missing_tokens }}</div>
            </div>

            <form method="POST">
                {% csrf_token %}

                <button type="submit" class="btn btn-info" formaction="{% url 'miningop:authenticate_view' mining_op_id=mining_op.id %}">
                    {% trans "Authenticate" %}
                </button>
            </form>
        </div>
    {% endif %}

    <div class="panel panel-primary">
        <div class="panel-heading" style="display: flex; align-items: center; justify-content: space-between;">
            <h3 class="panel-title">{% trans "Information" %}</h3>

            {% if can_manage and not mining_op.completed_at %}
                <form method="POST">
                    {% csrf_token %}

                    {% if not mining_op.started_at %}
                        <button type="submit" class="btn btn-sm btn-info" formaction="{% url 'miningop:start' mining_op_id=mining_op.id %}">
                            {% trans "Start op" %}
                        </button>
                    {% endif %}

                    {% if mining_op.started_at and not mining_op.completed_at %}
                        <button type="submit" class="btn btn-sm btn-info" formaction="{% url 'miningop:refresh' mining_op_id=mining_op.id %}" style="margin-right: 10px;">
                            {% trans "Refresh op" %}
                        </button>

                        <button type="submit" class="btn btn-sm btn-info" formaction="{% url 'miningop:complete' mining_op_id=mining_op.id %}">
                            {% trans "End op" %}
                        </button>
                    {% endif %}
                </form>
            {% endif %}
        </div>
        <div class="panel-body" style="min-height: 100px;">
            <div class="row">
                <div class="col-xs-4">
                    <strong>{% trans "Fleet commander" %}</strong>
                    <p>
                        {% if mining_op.fleet_commander.alliance_ticker %}
                            {{ mining_op.fleet_commander.alliance_ticker }}
                        {% endif %}
                        [{{ mining_op.fleet_commander.corporation_ticker }}]
                        {{ mining_op.fleet_commander.character_name }}
                    </p>
                </div>

                <div class="col-xs-4">
                    <strong>{% trans "Operation Status" %}</strong>
                    <p>{{ mining_op.status }}</p>
                </div>
            </div>

            <div class="row">
                <div class="col-xs-4">
                    <strong>{% trans "Created" %}</strong>
                    <p>{{ mining_op.created_at | date:"Y-M-d H:i" }}</p>
                </div>

                <div class="col-xs-4">
                    <strong>{% trans "Started" %}</strong>
                    <p>{{ mining_op.started_at | date:"Y-M-d H:i" }}</p>
                </div>

                <div class="col-xs-4">
                    <strong>{% trans "Completed" %}</strong>
                    <p>{{ mining_op.completed_at | date:"Y-M-d H:i" }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-primary">
        <div class="panel-heading" style="display: flex; align-items: center; justify-content: space-between;">
            <h3 class="panel-title">{% trans "Members" %}</h3>

            {% if update_timedelta %}
                <div>
                    <span>{% trans "Next update in " %}</span>
                    <span id="countdown" attr-seconds="{{ update_timedelta }}" attr-interval="{{ update_interval }}">
                        {{ update_timedelta }} {% trans "seconds" %}
                    </span>
                </div>
            {% endif %}
        </div>
        <div class="panel-body" style="min-height: 100px;">
            {% if mining_op.members.exists %}
                <div class="table-responsive">
                    <table class="table mining-op-list">
                        <thead>
                            <th class="text-center">{% trans "Member" %}</th>
                            <th class="text-center">{% trans "Joined" %}</th>
                            <th class="text-center">{% trans "Status" %}</th>
                            <th class="text-center">{% trans "Units mined" %}</th>
                            <th class="text-center">{% trans "Payout" %}</th>
                            <th></th>
                        </thead>

                        <tbody>
                        {% for member in mining_op.members.all %}
                            <tr>
                                <td class="text-center">
                                    {% if member.character.alliance_ticker %}
                                        {{ member.character.alliance_ticker }}
                                    {% endif %}
                                    [{{ member.character.corporation_ticker }}]
                                    {{ member.character.character_name }}
                                </td>
                                <td class="text-center">
                                    {{ member.created_at | date:"Y-M-d H:i" }}
                                </td>
                                <td class="text-center">
                                    {% if not member.ledger_token %}
                                        <span class="text-danger">{% trans "No valid tokens" %}</span>
                                    {% elif member.initial_ledger is None %}
                                        <span class="text-warning">{% trans "No initial ledger" %}</span>
                                    {% else %}
                                        <abbr title="Initial ledger fetched at {{ member.initial_ledger_fetched_at | date:'Y-M-d H:i' }}" class="text-success">{% trans "Good to go" %}</span>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {{ member.ledger_diff.total_units | intcomma }}
                                </td>
                                <td class="text-center">
                                    {{ member.ledger_diff.total_payout | floatformat:0 | intcomma }} ISK
                                </td>
                                <td class="text-center">
                                    <a href="#details-{{ member.id }}" data-toggle="collapse">
                                        {% trans "Details" %}
                                    </a>
                                </td>
                            </tr>

                            <tr>
                                <td colspan="6" style="padding: 0;">
                                    <div class="collapse" id="details-{{ member.id }}">
                                        {% if is_night_mode %}
                                            <div class="row" style="background-color: rgb(66, 66, 66); padding-top: 10px; margin: 0;">
                                        {% else %}
                                            <div class="row" style="background-color: rgb(240, 240, 240); padding-top: 10px; margin: 0;">
                                        {% endif %}
                                            {% for detail in member.ledger_diff.details %}
                                                <div class="col-xs-3" style="display: flex; align-items: center; justify-content: center; margin-bottom: 10px;">
                                                    <img src="https://images.evetech.net/types/{{ detail.type_id }}/icon" alt="{{ detail.name }}" height="48" width="48" />

                                                    <div style="margin-left: 20px; font-size: 0.8em;">
                                                        <div>{{ detail.name }}</div>
                                                        <div>{{ detail.volume | floatformat:2 | intcomma }} m&sup3;</div>
                                                        <div>{{ detail.price_total | floatformat:0 | intcomma }} ISK</div>
                                                    </div>
                                                </div>
                                            {% endfor %}

                                            {% if not member.ledger_diff.details %}
                                                <p class="text-center text-muted"><i>{% trans "No mining done yet." %}</i></p>
                                            {% endif %}
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}

                            <tr>
                                <td colspan="6">
                                    <hr />
                                </td>
                            </tr>

                            <tr>
                                <td class="text-center">
                                    {% trans "Total" %}
                                </td>
                                <td></td>
                                <td></td>
                                <td class="text-center">
                                    {{ mining_op.total_units | intcomma }}
                                </td>
                                <td class="text-center">
                                    {{ mining_op.total_payout | floatformat:0 | intcomma }} ISK
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="alert alert-warning text-center">
                    {% trans "No members yet." %}
                </div>
            {% endif %}
        </div>
    </div>

    <script type="application/javascript">
        function update(secondsToUpdate) {
            var duration = '';
            if (secondsToUpdate > 60) {
                var minutes = Math.floor(secondsToUpdate / 60);
                var seconds = secondsToUpdate % 60;
                duration = minutes + ' minute' + (minutes > 1 ? 's' : '') + ', ' + seconds + ' second' + (seconds > 1 ? 's' : '');
            } else {
                duration = secondsToUpdate + ' second' + (secondsToUpdate > 1 ? 's' : '');
            }

            countdown.innerHTML = duration;
        }

        function start() {
            var countdown = document.getElementById('countdown');
            if (!countdown) return;

            var secondsToUpdate = parseInt(countdown.getAttribute('attr-seconds'), 10);
            var updateInterval = parseInt(countdown.getAttribute('attr-interval'), 10);

            update(secondsToUpdate);

            setInterval(function() {
                update(secondsToUpdate);
                secondsToUpdate--;

                if (secondsToUpdate <= 0) secondsToUpdate = updateInterval;
            }, 1000);
        }

        start();
    </script>

{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block extra_script %}
{% endblock %}